name = "bproject"
compatibility_date = "2025-01-01"

pages_build_output_dir = "."
functions = "./functions"

# KV Binding
[[kv_namespaces]]
binding = "LOGIN_DATA"
id = "c1df5a8b70bf4b3094c54b6819f17020"
